### ISSUE TITLE
绝对路径生成不完整

### ISSUE THREAD

**Issue by ETRD** [CodeFalling/hexo-asset-image#13]
我使用该插件仍旧无法正常显示图片，查看html发现图片路径生成不完整，只有日，没有年月。
如下
img src="/22/imagetest/500.jpg" alt="500"

md文件完整语句如下：
---
title: imagetest
date: 2017-01-22 20:24:21
tags:
---

![500](imagetest\500.jpg)

请问如何解决？谢谢

**Comment by ETRD** [comment]
我将安装后的hexo-asset-image插件中的index.js中的这句代码
`var beginPos = getPosition(link, '/', 3) + 1;`
修改成了
`var beginPos = getPosition(link, '/', 1) + 1;`
问题得到解决，但不明白是不是巧合，也不明白其中的原理，更详细的见我的总结：
[hexo中完美插入本地图片](http://etrd.org/2017/01/23/hexo%E4%B8%AD%E5%AE%8C%E7%BE%8E%E6%8F%92%E5%85%A5%E6%9C%AC%E5%9C%B0%E5%9B%BE%E7%89%87/)

**Comment by smallx** [comment]
@ETRD 我用的 hexo 3.1.1 暂时没这个问题。看你的版本是 hexo 3.2，不知道是不是 hexo 版本的原因。

**Comment by LiuZhe6** [comment]
使用的hexo 3.2.2，在进行hexo g时出现错误。代码如下：
$ hexo g
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (D:\Hexo\blog\node_modules\hexo-asset-image\index.js:31:38)
    at exports.each (D:\Hexo\blog\node_modules\cheerio\lib\api\traversing.js:293:24)
    at Hexo.<anonymous> (D:\Hexo\blog\node_modules\hexo-asset-image\index.js:29:16)
    at Hexo.tryCatcher (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Hexo.<anonymous> (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\method.js:15:34)
    at D:\Hexo\blog\node_modules\hexo\lib\extend\filter.js:68:35
    at tryCatcher (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at ReductionPromiseArray._promiseFulfilled (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\reduce.js:105:38)
    at Promise._settlePromiseAt (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:589:26)
    at Promise._settlePromises (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
FATAL Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (D:\Hexo\blog\node_modules\hexo-asset-image\index.js:31:38)
    at exports.each (D:\Hexo\blog\node_modules\cheerio\lib\api\traversing.js:293:24)
    at Hexo.<anonymous> (D:\Hexo\blog\node_modules\hexo-asset-image\index.js:29:16)
    at Hexo.tryCatcher (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Hexo.<anonymous> (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\method.js:15:34)
    at D:\Hexo\blog\node_modules\hexo\lib\extend\filter.js:68:35
    at tryCatcher (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at ReductionPromiseArray._promiseFulfilled (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\reduce.js:105:38)
    at Promise._settlePromiseAt (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:589:26)
    at Promise._settlePromises (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (D:\Hexo\blog\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)



不知道如何解决？
